_target_: src.models.capmix_lit_module.CapMixLitModule

net:
  _target_: src.models.components.resnet.ResNet
  model_name: "resnet50"
  pretrained: False
  num_classes: ${model.num_classes}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: "max"
  factor: 0.1
  patience: 10

num_classes: 10