_target_: src.models.mixaug_lit_module.MixAugLitModule

num_classes: 10

net:
  _target_: src.models.components.resnet.ResNet
  model_name: "resnet50"
  pretrained: false
  num_classes: ${model.num_classes}

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.1
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: "max"
  factor: 0.1
  patience: 10
